### ISSUE TITLE
location of lock-body-scroll.min.js

### ISSUE THREAD

**Issue by Franz-Kafka** [clarkdo/lock-body-scroll#1]
I would like to use this in a web project. 
Where can I find the "lock-body-scroll.min.js" as you wrote in the installation guide?

**Comment by clarkdo** [comment]
Sorry for the confusion, I'll update the readme, the file you can find in https://unpkg.com/lock-body-scroll or https://cdn.jsdelivr.net/npm/lock-body-scroll
